# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.get_developer_feature_flags401_response import GetDeveloperFeatureFlags401Response

class TestGetDeveloperFeatureFlags401Response(unittest.TestCase):
    """GetDeveloperFeatureFlags401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDeveloperFeatureFlags401Response:
        """Test GetDeveloperFeatureFlags401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDeveloperFeatureFlags401Response`
        """
        model = GetDeveloperFeatureFlags401Response()
        if include_optional:
            return GetDeveloperFeatureFlags401Response(
                message = '',
                exception = ''
            )
        else:
            return GetDeveloperFeatureFlags401Response(
                message = '',
        )
        """

    def testGetDeveloperFeatureFlags401Response(self):
        """Test GetDeveloperFeatureFlags401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
