# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.diligence_category import DiligenceCategory

class TestDiligenceCategory(unittest.TestCase):
    """DiligenceCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiligenceCategory(self):
        """Test DiligenceCategory"""
        # inst = DiligenceCategory()

if __name__ == '__main__':
    unittest.main()
