# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.api.bank_account_api import BankAccountApi


class TestBankAccountApi(unittest.TestCase):
    """BankAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_bank_account(self) -> None:
        """Test case for get_bank_account

        Get a bank account (BankAccountModel)
        """
        pass


if __name__ == '__main__':
    unittest.main()
