# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_transaction_rollup_status(self) -> None:
        """Test case for get_transaction_rollup_status

        Retrieve a single transaction rollup status by batch ID
        """
        pass

    def test_get_transaction_rollup_statuses(self) -> None:
        """Test case for get_transaction_rollup_statuses

        Retrieves the status of transaction rollups by batch IDs
        """
        pass


if __name__ == '__main__':
    unittest.main()
