# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.object_authorized_class import ObjectAuthorizedClass

class TestObjectAuthorizedClass(unittest.TestCase):
    """ObjectAuthorizedClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectAuthorizedClass(self):
        """Test ObjectAuthorizedClass"""
        # inst = ObjectAuthorizedClass()

if __name__ == '__main__':
    unittest.main()
