# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.distribution_batch import DistributionBatch

class TestDistributionBatch(unittest.TestCase):
    """DistributionBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistributionBatch:
        """Test DistributionBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistributionBatch`
        """
        model = DistributionBatch()
        if include_optional:
            return DistributionBatch(
                id = 56,
                total_amount = 42.00,
                arena_id = 56,
                entity_id = 56
            )
        else:
            return DistributionBatch(
                id = 56,
                total_amount = 42.00,
                arena_id = 56,
                entity_id = 56,
        )
        """

    def testDistributionBatch(self):
        """Test DistributionBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
