# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.business_info_institution_profiles_inner import BusinessInfoInstitutionProfilesInner

class TestBusinessInfoInstitutionProfilesInner(unittest.TestCase):
    """BusinessInfoInstitutionProfilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BusinessInfoInstitutionProfilesInner:
        """Test BusinessInfoInstitutionProfilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BusinessInfoInstitutionProfilesInner`
        """
        model = BusinessInfoInstitutionProfilesInner()
        if include_optional:
            return BusinessInfoInstitutionProfilesInner(
                external_profile_id = 1,
                legal_entity_name = 'Juniper Square',
                tax_id = '123456789',
                date_of_organization = '2024-04-26',
                is_beneficial_owner = True,
                address = main_openapi_client.models.institution_profile_address.InstitutionProfile_address(),
                documents = [
                    main_openapi_client.models.business_info_documents_inner.BusinessInfo_documents_inner()
                    ],
                business_ownership_percent = 30
            )
        else:
            return BusinessInfoInstitutionProfilesInner(
                external_profile_id = 1,
                legal_entity_name = 'Juniper Square',
                tax_id = '123456789',
                date_of_organization = '2024-04-26',
                address = main_openapi_client.models.institution_profile_address.InstitutionProfile_address(),
                documents = [
                    main_openapi_client.models.business_info_documents_inner.BusinessInfo_documents_inner()
                    ],
        )
        """

    def testBusinessInfoInstitutionProfilesInner(self):
        """Test BusinessInfoInstitutionProfilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
