# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.api.distribution_batches_api import DistributionBatchesApi


class TestDistributionBatchesApi(unittest.TestCase):
    """DistributionBatchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DistributionBatchesApi()

    def tearDown(self) -> None:
        pass

    def test_get_distribution_batch(self) -> None:
        """Test case for get_distribution_batch

        Get distribution batch no authorization checks
        """
        pass

    def test_get_distributions_for_distribution_batch(self) -> None:
        """Test case for get_distributions_for_distribution_batch

        Get distributions for a distribution batch not authorization checks
        """
        pass


if __name__ == '__main__':
    unittest.main()
