# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.create_diligence_business_info import CreateDiligenceBusinessInfo

class TestCreateDiligenceBusinessInfo(unittest.TestCase):
    """CreateDiligenceBusinessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDiligenceBusinessInfo:
        """Test CreateDiligenceBusinessInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDiligenceBusinessInfo`
        """
        model = CreateDiligenceBusinessInfo()
        if include_optional:
            return CreateDiligenceBusinessInfo(
                external_profile_id = 1,
                legal_entity_name = 'Juniper Square',
                date_of_organization = '2024-04-26',
                tax_id = '123456789',
                documents = [
                    main_openapi_client.models.business_info_documents_inner.BusinessInfo_documents_inner()
                    ],
                address = main_openapi_client.models.business_info_address.BusinessInfo_address(),
                individual_profiles = [
                    main_openapi_client.models.business_info_individual_profiles_inner.BusinessInfo_individual_profiles_inner()
                    ],
                institution_profiles = [
                    main_openapi_client.models.business_info_institution_profiles_inner.BusinessInfo_institution_profiles_inner()
                    ]
            )
        else:
            return CreateDiligenceBusinessInfo(
        )
        """

    def testCreateDiligenceBusinessInfo(self):
        """Test CreateDiligenceBusinessInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
