# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.business_info_individual_profiles_inner import BusinessInfoIndividualProfilesInner

class TestBusinessInfoIndividualProfilesInner(unittest.TestCase):
    """BusinessInfoIndividualProfilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BusinessInfoIndividualProfilesInner:
        """Test BusinessInfoIndividualProfilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BusinessInfoIndividualProfilesInner`
        """
        model = BusinessInfoIndividualProfilesInner()
        if include_optional:
            return BusinessInfoIndividualProfilesInner(
                external_profile_id = 1,
                first_name = 'John',
                last_name = 'Doe',
                date_of_birth = '2024-04-26',
                tax_id = '123456789',
                address = main_openapi_client.models.individual_profile_address.IndividualProfile_address(),
                documents = [
                    main_openapi_client.models.business_info_documents_inner.BusinessInfo_documents_inner()
                    ],
                is_beneficial_owner = True,
                is_controller = True,
                is_signatory = True,
                business_ownership_percent = 30
            )
        else:
            return BusinessInfoIndividualProfilesInner(
                external_profile_id = 1,
                first_name = 'John',
                last_name = 'Doe',
                date_of_birth = '2024-04-26',
                tax_id = '123456789',
                address = main_openapi_client.models.individual_profile_address.IndividualProfile_address(),
                documents = [
                    main_openapi_client.models.business_info_documents_inner.BusinessInfo_documents_inner()
                    ],
        )
        """

    def testBusinessInfoIndividualProfilesInner(self):
        """Test BusinessInfoIndividualProfilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
