# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.transaction_rollup_status import TransactionRollupStatus

class TestTransactionRollupStatus(unittest.TestCase):
    """TransactionRollupStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionRollupStatus:
        """Test TransactionRollupStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionRollupStatus`
        """
        model = TransactionRollupStatus()
        if include_optional:
            return TransactionRollupStatus(
                sync_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'received'
            )
        else:
            return TransactionRollupStatus(
        )
        """

    def testTransactionRollupStatus(self):
        """Test TransactionRollupStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
