# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.contact_details_attributes_address_inner_address_state import ContactDetailsAttributesAddressInnerAddressState

class TestContactDetailsAttributesAddressInnerAddressState(unittest.TestCase):
    """ContactDetailsAttributesAddressInnerAddressState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactDetailsAttributesAddressInnerAddressState:
        """Test ContactDetailsAttributesAddressInnerAddressState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactDetailsAttributesAddressInnerAddressState`
        """
        model = ContactDetailsAttributesAddressInnerAddressState()
        if include_optional:
            return ContactDetailsAttributesAddressInnerAddressState(
                object_id = 56,
                object_name = 'dddd',
                object_type = ''
            )
        else:
            return ContactDetailsAttributesAddressInnerAddressState(
        )
        """

    def testContactDetailsAttributesAddressInnerAddressState(self):
        """Test ContactDetailsAttributesAddressInnerAddressState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
