# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.object_type import ObjectType

class TestObjectType(unittest.TestCase):
    """ObjectType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectType(self):
        """Test ObjectType"""
        # inst = ObjectType()

if __name__ == '__main__':
    unittest.main()
