# coding: utf-8

"""
    Juniper Square Internal API

    An internal API for inter-service communication at JSQ.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from main_openapi_client.models.arena import Arena

class TestArena(unittest.TestCase):
    """Arena unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Arena:
        """Test Arena
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Arena`
        """
        model = Arena()
        if include_optional:
            return Arena(
                id = 56,
                name = 'Rockstone Capital',
                unified_portal_url = 'app.dev.junipersquare.com/i/rockstone',
                is_active = True,
                domain = 'investors.rockstonecap.com'
            )
        else:
            return Arena(
                id = 56,
                name = 'Rockstone Capital',
                unified_portal_url = 'app.dev.junipersquare.com/i/rockstone',
                is_active = True,
                domain = 'investors.rockstonecap.com',
        )
        """

    def testArena(self):
        """Test Arena"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
